### ISSUE TITLE
NGN.NET Resource.json() method - Allow configuration

### ISSUE THREAD

**Issue by gbdrummer** [ngnjs/net#8]
**Is your feature request related to a problem? Please describe.**
The `get()` method allows passing in a configuration object to set parameters on the Request, but the `json()` method does not.

**Describe the solution you'd like**
I'd like to be able to pass in a config object as an optional second parameter.

**Describe alternatives you've considered**
NONE

**Additional context**
I need to be able to run a request with `mode: no-cors` for local development. I could just use the `get()` method but I would like to take advantage of the `json()` method's automatic JSON parsing.

**Comment by gbdrummer** [comment]
As an addendum, it might also be useful to be able to specify a `mode` parameter on the Resource itself so we don't have to add it to every request manually.

**Comment by coreybutler** [comment]
While related, the addendum should probably be a separate issue so we can track the progress and assure it gets included.

**Comment by gbdrummer** [comment]
Agreed- I created a new issue for the addendum here: https://github.com/ngnjs/net/issues/9

**Comment by coreybutler** [comment]
This has been resolved. Now the JSON method will accept a string or configuration attribute, just like the other request methods. This does not apply to JSONP, which works differently.
